// Generiert aus devicon.json (v2.17.0). Nicht von Hand pflegen.
export const DEVICON_NAMES: string[] = [
  "aarch64",
  "adonisjs",
  "aerospike",
  "aframe",
  "aftereffects",
  "akka",
  "algolia",
  "almalinux",
  "alpinejs",
  "amazonwebservices",
  "anaconda",
  "android",
  "androidstudio",
  "angular",
  "angularjs",
  "angularmaterial",
  "ansible",
  "ansys",
  "antdesign",
  "apache",
  "apacheairflow",
  "apachekafka",
  "apachespark",
  "apex",
  "apl",
  "apollographql",
  "appcelerator",
  "apple",
  "appwrite",
  "archlinux",
  "arduino",
  "argocd",
  "artixlinux",
  "astro",
  "atom",
  "awk",
  "axios",
  "azure",
  "azuredevops",
  "azuresqldatabase",
  "babel",
  "babylonjs",
  "backbonejs",
  "ballerina",
  "bamboo",
  "bash",
  "bazel",
  "beats",
  "behance",
  "bevyengine",
  "biome",
  "bitbucket",
  "blazor",
  "blender",
  "bootstrap",
  "bower",
  "browserstack",
  "bulma",
  "bun",
  "c",
  "cairo",
  "cakephp",
  "canva",
  "capacitor",
  "carbon",
  "cassandra",
  "centos",
  "ceylon",
  "chakraui",
  "chartjs",
  "chrome",
  "circleci",
  "clarity",
  "clickhouse",
  "clion",
  "clojure",
  "clojurescript",
  "cloudflare",
  "cloudflareworkers",
  "cloudrun",
  "cmake",
  "cobol",
  "codeac",
  "codecov",
  "codeigniter",
  "codepen",
  "coffeescript",
  "composer",
  "confluence",
  "consul",
  "contao",
  "corejs",
  "cosmosdb",
  "couchbase",
  "couchdb",
  "cpanel",
  "cplusplus",
  "crystal",
  "csharp",
  "css3",
  "cucumber",
  "cypressio",
  "d3js",
  "dart",
  "datadog",
  "datagrip",
  "dataspell",
  "datatables",
  "dbeaver",
  "debian",
  "delphi",
  "denojs",
  "detaspace",
  "devicon",
  "digitalocean",
  "discloud",
  "discordjs",
  "django",
  "djangorest",
  "docker",
  "doctrine",
  "dot-net",
  "dotnetcore",
  "dovecot",
  "dreamweaver",
  "dropwizard",
  "drupal",
  "duckdb",
  "dyalog",
  "dynamodb",
  "dynatrace",
  "eclipse",
  "ecto",
  "elasticsearch",
  "electron",
  "eleventy",
  "elixir",
  "elm",
  "emacs",
  "embeddedc",
  "ember",
  "entityframeworkcore",
  "envoy",
  "erlang",
  "eslint",
  "expo",
  "express",
  "facebook",
  "fastapi",
  "fastify",
  "faunadb",
  "feathersjs",
  "fedora",
  "fiber",
  "figma",
  "filamentphp",
  "filezilla",
  "firebase",
  "firebird",
  "firefox",
  "flask",
  "flutter",
  "forgejo",
  "fortran",
  "foundation",
  "framermotion",
  "framework7",
  "fsharp",
  "fusion",
  "gardener",
  "gatling",
  "gatsby",
  "gazebo",
  "gcc",
  "gentoo",
  "ghost",
  "gimp",
  "git",
  "gitbook",
  "github",
  "githubactions",
  "githubcodespaces",
  "gitkraken",
  "gitlab",
  "gitpod",
  "gitter",
  "gleam",
  "glitch",
  "go",
  "godot",
  "goland",
  "google",
  "googlecloud",
  "googlecolab",
  "gradle",
  "grafana",
  "grails",
  "graphql",
  "groovy",
  "grpc",
  "grunt",
  "gulp",
  "hadoop",
  "handlebars",
  "harbor",
  "hardhat",
  "harvester",
  "haskell",
  "haxe",
  "helm",
  "heroku",
  "hibernate",
  "homebrew",
  "hoppscotch",
  "html5",
  "htmx",
  "hugo",
  "hyperv",
  "ie10",
  "ifttt",
  "illustrator",
  "inertiajs",
  "influxdb",
  "inkscape",
  "insomnia",
  "intellij",
  "ionic",
  "jaegertracing",
  "jamstack",
  "jasmine",
  "java",
  "javascript",
  "jeet",
  "jekyll",
  "jenkins",
  "jest",
  "jetbrains",
  "jetpackcompose",
  "jhipster",
  "jira",
  "jiraalign",
  "jquery",
  "json",
  "jule",
  "julia",
  "junit",
  "jupyter",
  "k3os",
  "k3s",
  "k6",
  "kaggle",
  "kaldi",
  "kalilinux",
  "karatelabs",
  "karma",
  "kdeneon",
  "keras",
  "kibana",
  "knexjs",
  "knockout",
  "kotlin",
  "krakenjs",
  "ktor",
  "kubeflow",
  "kubernetes",
  "labview",
  "laminas",
  "laravel",
  "laraveljetstream",
  "latex",
  "leetcode",
  "less",
  "libgdx",
  "linkedin",
  "linux",
  "linuxmint",
  "liquibase",
  "livewire",
  "llvm",
  "lodash",
  "logstash",
  "love2d",
  "lua",
  "lumen",
  "magento",
  "mapbox",
  "mariadb",
  "markdown",
  "materializecss",
  "materialui",
  "matlab",
  "matplotlib",
  "mattermost",
  "maven",
  "maya",
  "memcached",
  "mercurial",
  "meteor",
  "microsoftsqlserver",
  "minitab",
  "mithril",
  "mobx",
  "mocha",
  "modx",
  "moleculer",
  "mongodb",
  "mongoose",
  "monogame",
  "moodle",
  "msdos",
  "mysql",
  "nano",
  "nats",
  "neo4j",
  "neovim",
  "nestjs",
  "netbeans",
  "netbox",
  "netlify",
  "networkx",
  "newrelic",
  "nextjs",
  "nginx",
  "ngrok",
  "ngrx",
  "nhibernate",
  "nim",
  "nimble",
  "nixos",
  "nodejs",
  "nodemon",
  "nodered",
  "nodewebkit",
  "nomad",
  "norg",
  "notion",
  "npm",
  "npss",
  "nuget",
  "numpy",
  "nuxt",
  "nuxtjs",
  "oauth",
  "objectivec",
  "ocaml",
  "ohmyzsh",
  "okta",
  "openal",
  "openapi",
  "opencl",
  "opencv",
  "opengl",
  "openstack",
  "opensuse",
  "opentelemetry",
  "opera",
  "oracle",
  "ory",
  "p5js",
  "packer",
  "pandas",
  "passport",
  "perl",
  "pfsense",
  "phalcon",
  "phoenix",
  "photonengine",
  "photoshop",
  "php",
  "phpstorm",
  "pixijs",
  "playwright",
  "plotly",
  "pm2",
  "pnpm",
  "podman",
  "poetry",
  "polygon",
  "portainer",
  "postcss",
  "postgresql",
  "postman",
  "powershell",
  "premierepro",
  "primeng",
  "prisma",
  "processing",
  "processwire",
  "prolog",
  "prometheus",
  "protractor",
  "proxmox",
  "pug",
  "pulsar",
  "pulumi",
  "puppeteer",
  "purescript",
  "putty",
  "pycharm",
  "pypi",
  "pyscript",
  "pytest",
  "python",
  "pytorch",
  "qodana",
  "qt",
  "qtest",
  "quarkus",
  "quasar",
  "qwik",
  "r",
  "rabbitmq",
  "racket",
  "radstudio",
  "rails",
  "railway",
  "rancher",
  "raspberrypi",
  "reach",
  "react",
  "reactbootstrap",
  "reactnative",
  "reactnavigation",
  "reactrouter",
  "readthedocs",
  "realm",
  "rect",
  "redhat",
  "redis",
  "redux",
  "reflex",
  "remix",
  "renpy",
  "replit",
  "rexx",
  "rider",
  "rocksdb",
  "rockylinux",
  "rollup",
  "ros",
  "rspec",
  "rstudio",
  "ruby",
  "rubymine",
  "rust",
  "rxjs",
  "safari",
  "salesforce",
  "sanity",
  "sass",
  "scala",
  "scalingo",
  "scikitlearn",
  "sdl",
  "selenium",
  "sema",
  "sentry",
  "sequelize",
  "shopware",
  "shotgrid",
  "sketch",
  "slack",
  "socketio",
  "solidity",
  "solidjs",
  "sonarqube",
  "sourceengine",
  "sourcetree",
  "spack",
  "spicedb",
  "splunk",
  "spring",
  "spss",
  "spyder",
  "sqlalchemy",
  "sqldeveloper",
  "sqlite",
  "ssh",
  "stackblitz",
  "stackoverflow",
  "stata",
  "stenciljs",
  "storybook",
  "streamlit",
  "styledcomponents",
  "stylus",
  "subversion",
  "sulu",
  "supabase",
  "surrealdb",
  "svelte",
  "svgo",
  "swagger",
  "swift",
  "swiper",
  "symfony",
  "tailwindcss",
  "talos",
  "tauri",
  "teleport",
  "tensorflow",
  "terraform",
  "terramate",
  "tex",
  "thealgorithms",
  "threedsmax",
  "threejs",
  "thymeleaf",
  "titaniumsdk",
  "tmux",
  "tomcat",
  "tortoisegit",
  "towergit",
  "traefikmesh",
  "traefikproxy",
  "travis",
  "trello",
  "trpc",
  "turbo",
  "twilio",
  "twitter",
  "typescript",
  "typo3",
  "ubuntu",
  "unifiedmodelinglanguage",
  "unity",
  "unix",
  "unrealengine",
  "uwsgi",
  "v8",
  "vaadin",
  "vagrant",
  "vala",
  "vault",
  "veevalidate",
  "vercel",
  "vertx",
  "vim",
  "visualbasic",
  "visualstudio",
  "vite",
  "vitejs",
  "vitess",
  "vitest",
  "vscode",
  "vscodium",
  "vsphere",
  "vuejs",
  "vuestorefront",
  "vuetify",
  "vulkan",
  "vyper",
  "waku",
  "wasm",
  "web3js",
  "webflow",
  "webgpu",
  "weblate",
  "webpack",
  "webstorm",
  "windows11",
  "windows8",
  "wolfram",
  "woocommerce",
  "wordpress",
  "xamarin",
  "xcode",
  "xd",
  "xml",
  "yaml",
  "yarn",
  "yii",
  "yugabytedb",
  "yunohost",
  "zend",
  "zig",
  "zsh",
  "zustand",
];
export const DEVICON_TAGS: Record<string, string[]> = {
  "aarch64": ["architecture", "programming", "language", "ARM"],
  "adonisjs": ["nodejs", "framework"],
  "aerospike": ["data", "database", "nosql"],
  "aframe": ["framework", "html", "javascript", "js", "web"],
  "aftereffects": ["video", "editor"],
  "akka": ["framework", "java", "scala", "open-source"],
  "algolia": ["algorithms", "api", "documentation", "tool"],
  "almalinux": ["linux", "os", "open-source"],
  "alpinejs": ["framework", "javascript"],
  "amazonwebservices": ["cloud", "hosting", "server"],
  "anaconda": ["python", "data-science"],
  "android": ["os", "mobile"],
  "androidstudio": ["application", "editor", "jetbrains", "ide", "android", "mobile"],
  "angular": ["framework", "javascript"],
  "angularjs": ["framework", "javascript"],
  "angularmaterial": ["framework", "javascript"],
  "ansible": ["automation", "provisioning", "deployment", "continuous-delivery"],
  "ansys": ["simulation"],
  "antdesign": ["reactjs", "design", "language"],
  "apache": ["php"],
  "apacheairflow": ["platform", "pipeline", "orchestrator", "open-source"],
  "apachekafka": ["streaming", "open-source"],
  "apachespark": ["data-processing", "data-science", "machine-learning"],
  "apex": ["language"],
  "apl": ["programming", "language", "open-source", "cross-platform"],
  "apollographql": ["platform", "graphql", "api"],
  "appcelerator": ["app", "mobile"],
  "apple": ["brand", "mobile"],
  "appwrite": ["cloud", "platform", "server"],
  "archlinux": ["linux", "distribution", "desktop"],
  "arduino": ["microcontroller", "hardware"],
  "argocd": ["gitops", "continuous-delivery"],
  "artixlinux": ["linux", "os", "distribution", "desktop"],
  "astro": ["static site generator", "framework", "web-development"],
  "atom": ["editor"],
  "awk": ["programming", "language", "unix"],
  "axios": ["http", "promise", "nodejs"],
  "azure": ["cloud", "devops"],
  "azuredevops": ["azure", "devops", "cloud", "version control", "vcs"],
  "azuresqldatabase": ["azure", "database", "tool", "sql"],
  "babel": ["javascript", "transpiler"],
  "babylonjs": ["3d", "javascript", "library", "web"],
  "backbonejs": ["javascript", "framework"],
  "ballerina": ["java", "cloud", "server", "networking"],
  "bamboo": ["platform", "integration", "server"],
  "bash": ["shell", "command", "scripting"],
  "bazel": ["build", "automation", "open-source"],
  "beats": ["elastic", "data-transfer"],
  "behance": ["social", "website"],
  "bevyengine": ["game-engine", "game", "rust", "open-source"],
  "biome": ["linter", "javascript", "typescript", "code-quality", "coding-style", "format"],
  "bitbucket": ["version-control"],
  "blazor": ["dotnet", ".net", "framework", "design", "ui"],
  "blender": ["modelling", "python", "3d", "animation"],
  "bootstrap": ["css", "framework", "html", "javascript", "library"],
  "bower": ["package", "manager"],
  "browserstack": ["website", "app", "testing", "tool"],
  "bulma": ["css", "framework"],
  "bun": ["javascript", "zig", "language"],
  "c": ["language"],
  "cairo": ["graphic", "library", "c", "open-source"],
  "cakephp": ["framework"],
  "canva": ["design"],
  "capacitor": ["javascript", "js", "ionic", "framework", "universal"],
  "carbon": ["programming", "language"],
  "cassandra": ["nosql", "database", "open-source"],
  "centos": ["server", "linux"],
  "ceylon": ["language"],
  "chakraui": ["ui", "library"],
  "chartjs": ["javascript", "chart", "framework"],
  "chrome": ["browser"],
  "circleci": ["integration", "platform"],
  "clarity": ["programming", "language", "blockchain"],
  "clickhouse": ["cloud", "column-oriented", "database", "warehouse"],
  "clion": ["jetbrains", "editor", "c", "c++", "cpp", "cplusplus"],
  "clojure": ["language", "jvm"],
  "clojurescript": ["language"],
  "cloudflare": ["web", "cdn", "dns", "proxy", "security"],
  "cloudflareworkers": ["platform", "serverless", "deploy", "performance", "javascript"],
  "cloudrun": ["platform", "serverless", "deploy", "cloud-computing-platform"],
  "cmake": ["build"],
  "cobol": ["language"],
  "codeac": ["platform", "integration"],
  "codecov": ["platform", "integration"],
  "codeigniter": ["php", "framework"],
  "codepen": ["social", "website", "editor"],
  "coffeescript": ["javascript", "transpiler", "language"],
  "composer": ["package", "manager", "php"],
  "confluence": ["collaboration", "documentation", "wiki"],
  "consul": ["networking", "infrastructure", "security", "tool"],
  "contao": ["cms"],
  "corejs": ["javascript", "library", "polyfill", "tool"],
  "cosmosdb": ["database", "nosql", "cloud", "azure"],
  "couchbase": ["database", "nosql", "cloud"],
  "couchdb": ["database"],
  "cpanel": ["hosting", "web hosting", "server", "control panel"],
  "cplusplus": ["language"],
  "crystal": ["programming", "language"],
  "csharp": ["language"],
  "css3": ["language", "programming"],
  "cucumber": ["framework"],
  "cypressio": ["testing", "framework"],
  "dart": ["programming", "language"],
  "datadog": ["monitoring", "platform", "integration"],
  "datagrip": ["jetbrains", "ide", "sql", "database"],
  "dataspell": ["jetbrains", "ide", "jupyter notebook", "data science"],
  "datatables": ["css", "framework", "html", "javascript", "library"],
  "dbeaver": ["tool", "database"],
  "debian": ["os", "server"],
  "delphi": ["language"],
  "denojs": ["javascript", "rust", "runtime"],
  "detaspace": ["cloud", "hosting", "server"],
  "devicon": ["iconset"],
  "digitalocean": ["cloud", "hosting", "database", "storage"],
  "discloud": ["cloud", "hosting", "database", "storage"],
  "discordjs": ["wrapper", "api_wrapper", "nodejs"],
  "djangorest": ["framework", "rest", "api", "python", "web"],
  "docker": ["platform", "deploy"],
  "dot-net": ["framework"],
  "dotnetcore": ["framework"],
  "dovecot": ["imap", "pop3", "e-mail"],
  "dreamweaver": ["web-development", "editor", "software", "tool"],
  "dropwizard": ["java", "framework"],
  "drupal": ["cms"],
  "duckdb": ["database", "sql"],
  "dyalog": ["language"],
  "dynamodb": ["key-value", "database", "java"],
  "dynatrace": ["monitoring", "performance", "cloud"],
  "eclipse": ["editor", "IDE"],
  "ecto": ["data", "elixir", "integration", "query"],
  "elasticsearch": ["elastic", "data", "logs"],
  "electron": ["framework"],
  "eleventy": ["ssg", "static site generator"],
  "elixir": ["language"],
  "elm": ["framework"],
  "emacs": ["editor"],
  "embeddedc": ["language", "programming"],
  "ember": ["framework", "javascript", "web-development", "build"],
  "entityframeworkcore": ["dotnet", ".net", "framework", "database"],
  "envoy": ["proxy", "cloud"],
  "eslint": ["linter", "javascript", "code-quality", "coding-style"],
  "expo": ["framework", "react", "react-native"],
  "express": ["framework"],
  "facebook": ["auth"],
  "fastapi": ["python", "framework"],
  "fastify": ["framework", "web", "node.js", "javascript", "performance"],
  "faunadb": ["database"],
  "feathersjs": ["framework", "rest"],
  "fedora": ["linux", "distribution", "desktop"],
  "fiber": ["framework", "go", "web"],
  "figma": ["design"],
  "filamentphp": ["framework", "laravel"],
  "filezilla": ["ftp"],
  "firebase": ["auth", "hosting", "storage", "cloud"],
  "firebird": ["database"],
  "firefox": ["browser"],
  "flask": ["python", "framework"],
  "flutter": ["framework", "sdk"],
  "forgejo": ["software", "git", "version-control"],
  "fortran": ["programming", "language"],
  "foundation": ["framework", "css"],
  "framermotion": ["library", "open-source", "react", "animation"],
  "framework7": ["framework", "cross-platform", "development", "mobile", "android", "ios"],
  "fsharp": ["language"],
  "fusion": ["design"],
  "gardener": ["kubernetes", "cloud"],
  "gatling": ["framework", "testing"],
  "gatsby": ["reactjs", "framework"],
  "gazebo": ["robotics", "3d"],
  "gcc": ["compiler", "linux"],
  "gentoo": ["linux", "distribution", "desktop"],
  "ghost": ["cms"],
  "gimp": ["graphic"],
  "git": ["version-control"],
  "gitbook": ["documentation", "pages", "git", "markup"],
  "github": ["version-control"],
  "githubactions": ["devops", "integration"],
  "githubcodespaces": ["development", "remote-development", "editor", "browser", "cloud"],
  "gitkraken": ["git", "version-control"],
  "gitlab": ["version-control"],
  "gitpod": ["open-source", "remote-development", "cloud", "IDE"],
  "gitter": ["social", "chat"],
  "gleam": ["language", "programming"],
  "glitch": ["web-apps", "online-platform", "programming-environment", "collaborative-environment"],
  "go": ["language"],
  "godot": ["game-engine", "open-source"],
  "goland": ["jetbrains", "ide", "go"],
  "google": ["auth"],
  "googlecloud": ["google", "cloud"],
  "googlecolab": ["cloud-computing-platform", "data science", "google", "machine-learning", "python", "virtual machine"],
  "gradle": ["open-source", "task-runner"],
  "grafana": ["monitoring", "analytics", "metrics", "logs", "visualization", "web-application"],
  "grails": ["framework", "groovy", "web-development", "jvm", "build"],
  "graphql": ["language", "data", "query"],
  "groovy": ["programming", "language", "jvm"],
  "grpc": ["programming", "c++", "java", "python", "go", "library"],
  "grunt": ["task-runner", "nodejs"],
  "gulp": ["task-runner", "nodejs"],
  "hadoop": ["framework", "big data", "open-source", "software", "library", "framework"],
  "handlebars": ["framework"],
  "harbor": ["docker", "artifact", "oci", "registry"],
  "hardhat": ["ethereum", "development", "solidity", "javascript", "typescript"],
  "harvester": ["kubernetes", "operating-system", "hypervisor", "rancher"],
  "haskell": ["language", "functional"],
  "haxe": ["language"],
  "helm": ["package", "manager", "kubernetes"],
  "heroku": ["cloud"],
  "hibernate": ["database", "framework", "java"],
  "homebrew": ["package", "manager", "linux", "apple", "os"],
  "hoppscotch": ["rest", "testing", "api"],
  "html5": ["programming", "language"],
  "htmx": ["framework", "web", "html", "ui"],
  "hugo": ["framework", "ssg", "static-site-generator", "go", "html", "css"],
  "hyperv": ["hypervisor", "operating-system"],
  "ie10": ["browser"],
  "ifttt": ["automation", "applets", "programming"],
  "illustrator": ["editor", "vector"],
  "inertiajs": ["javascript", "js", "library"],
  "influxdb": ["database", "monitoring", "open-source", "api"],
  "inkscape": ["editor", "vector"],
  "insomnia": ["open-source", "Rest API", "Soap API", "JSON-XML"],
  "intellij": ["jetbrains", "editor", "java"],
  "ionic": ["framework"],
  "jaegertracing": ["monitoring", "tracing"],
  "jamstack": ["javascript", "markup"],
  "jasmine": ["testing"],
  "java": ["programming", "language", "jvm"],
  "javascript": ["programming", "language"],
  "jeet": ["framework", "css"],
  "jekyll": ["ruby", "blog"],
  "jenkins": ["platform", "integration", "server"],
  "jest": ["testing", "javascript"],
  "jetbrains": ["ide"],
  "jetpackcompose": ["framework", "language", "kotlin", "android"],
  "jhipster": ["development", "framework", "java", "platform", "web", "web-application"],
  "jira": ["platform", "organize"],
  "jiraalign": ["development", "integration", "software"],
  "jquery": ["library", "javascript"],
  "json": ["format", "standard", "file-format", "object-notation"],
  "jule": ["programming", "language"],
  "julia": ["programming", "language"],
  "junit": ["testing", "framework", "java"],
  "jupyter": ["programming", "language"],
  "k3os": ["kubernetes", "operating-system", "k3s", "rancher"],
  "k3s": ["kubernetes", "container", "platform"],
  "k6": ["testing", "performance", "load"],
  "kaggle": ["platform", "auth", "machine-learning"],
  "kaldi": ["audio", "open-source", "library"],
  "kalilinux": ["linux", "operating-system", "security"],
  "karatelabs": ["framework", "testing"],
  "karma": ["testing", "test-runner"],
  "kdeneon": ["linux", "operating system", "open-source"],
  "keras": ["machine-learning", "python", "library"],
  "kibana": ["elastic", "dashboard"],
  "knexjs": ["database", "query", "sql", "javascript", "library"],
  "knockout": ["framework", "javascript"],
  "kotlin": ["language", "jetbrains", "jvm"],
  "krakenjs": ["nodejs", "framework"],
  "ktor": ["jetbrains", "kotlin", "framework"],
  "kubeflow": ["kubernetes", "deployment", "machine-learning"],
  "kubernetes": ["container", "deployment"],
  "labview": ["language"],
  "laminas": ["php", "framework", "web", "mvc", "middleware"],
  "laravel": ["php", "framework"],
  "laraveljetstream": ["php", "laravel", "tailwind", "scaffolding"],
  "latex": ["latex3", "latex2e", "markup", "tex", "typesetting-system"],
  "leetcode": ["online-platform", "coding-platform", "platform", "coding", "dsa", "interview-preparation"],
  "less": ["css", "pre-processor"],
  "libgdx": ["framework", "java", "game-development", "cross-platform", "open-source"],
  "linkedin": ["social", "auth"],
  "linux": ["os"],
  "linuxmint": ["os", "linux"],
  "liquibase": ["tool", "database"],
  "livewire": ["framework", "laravel", "php", "open-source"],
  "llvm": ["compiler", "framework", "c++", "open-source"],
  "lodash": ["javascript", "framework"],
  "logstash": ["logs", "elastic"],
  "love2d": ["programming", "game-engine"],
  "lua": ["programming", "language", "object-oriented", "scripting", "procedural", "prototype-based"],
  "lumen": ["laravel", "php", "framework", "micro-framework"],
  "magento": ["php", "framework"],
  "mapbox": ["map", "navigation", "data"],
  "mariadb": ["database", "sql", "open-source"],
  "markdown": ["markup", "language"],
  "materializecss": ["framework", "css", "design", "material-design"],
  "materialui": ["framework", "design", "ui"],
  "matlab": ["programming", "language"],
  "matplotlib": ["plotting", "library", "math", "visualization", "python", "api"],
  "mattermost": ["app", "chat", "collaboration", "open-source", "platform"],
  "maven": ["build"],
  "maya": ["mel", "pymel", "python", "3d", "programming", "vfx"],
  "memcached": ["data", "database", "nosql"],
  "mercurial": ["version-control"],
  "meteor": ["javascript", "framework"],
  "microsoftsqlserver": ["database", "sql", "db"],
  "minitab": ["package", "statistics"],
  "mithril": ["javascript", "framework", "frontend", "js"],
  "mobx": ["state-management", "testing", "reactjs", "nodejs"],
  "mocha": ["testing"],
  "modx": ["cms", "php", "framework"],
  "moleculer": ["nodejs", "javascript", "js", "microservices", "micro-services", "framework"],
  "mongodb": ["database"],
  "mongoose": ["data-model", "nodejs"],
  "monogame": ["engine", "game-engine", "C#", "c-sharp", "csharp"],
  "moodle": ["platform"],
  "msdos": ["os"],
  "mysql": ["database", "language"],
  "nano": ["text editor", "editor", "GNU", "terminal"],
  "nats": ["streaming", "open-source", "go"],
  "neo4j": ["database"],
  "neovim": ["text editor", "editor", "ide", "IDE", "open-source"],
  "nestjs": ["framework"],
  "netbeans": ["ide", "java", "open-source"],
  "netbox": ["network", "automation", "infrastructure", "open-source"],
  "netlify": ["cloud hosting", "serverless", "dynamic websites", "web applications", "open-source"],
  "networkx": ["graph", "library", "python"],
  "newrelic": ["monitoring", "observability", "analysis"],
  "nextjs": ["framework"],
  "nginx": ["server"],
  "ngrok": ["networking", "server"],
  "ngrx": ["state-management", "angular", "redux", "store", "javascript"],
  "nhibernate": ["library", "dotnet", ".net", "object-relational mapper", "orm", "C#"],
  "nim": ["programming", "functional", "object-oriented", "procedural"],
  "nimble": ["package-manager"],
  "nixos": ["os"],
  "nodejs": ["javascript", "language"],
  "nodemon": ["nodejs", "tool", "javascript"],
  "nodered": ["programming", "tool"],
  "nomad": ["container", "virtual machine", "deployment"],
  "norg": ["note-taking", "organization"],
  "notion": ["project-management"],
  "npm": ["package", "manager"],
  "nuget": ["package", "manager"],
  "numpy": ["library", "python"],
  "nuxt": ["js", "javascript", "framework", "fullstack", "vuejs"],
  "nuxtjs": ["js", "javascript", "framework", "frontend", "vuejs"],
  "oauth": ["authentication", "security"],
  "objectivec": ["programming", "language"],
  "ocaml": ["programming", "language"],
  "ohmyzsh": ["shell", "script", "scripting", "language", "command"],
  "okta": ["auth", "security"],
  "openal": ["library", "audio", "game", "3d"],
  "openapi": ["specification", "api", "open-source"],
  "opencl": ["framework", "language", "heterogeneous-computing", "cpp", "api", "khronos"],
  "opencv": ["library", "c/c++", "computer-vision"],
  "opengl": ["library", "graphics", "game", "3d"],
  "openstack": ["infrastructure-as-a-service", "cloud-computing-platform"],
  "opensuse": ["linux", "distribution", "desktop"],
  "opentelemetry": ["telemetry"],
  "opera": ["browser"],
  "oracle": ["database"],
  "ory": ["library", "open-source", "security"],
  "p5js": ["javascript", "js", "library"],
  "packer": ["infrastructure", "infrastructure-as-code", "continuous-delivery"],
  "pandas": ["library", "python"],
  "passport": ["authentication", "security"],
  "perl": ["programming", "language"],
  "pfsense": ["cloud", "network", "open-source", "security", "software"],
  "phalcon": ["php", "framework"],
  "phoenix": ["framework", "build", "web", "web-development", "development", "elixir"],
  "photonengine": ["game", "game-engine"],
  "photoshop": ["editor", "graphic"],
  "php": ["programming", "language"],
  "phpstorm": ["jetbrains", "editor", "php", "web", "html"],
  "pixijs": ["animation", "graphics", "html", "javascript", "library", "visualization"],
  "playwright": ["testing", "framework"],
  "plotly": ["frontend", "machine-learning", "dashboard"],
  "pm2": ["nodejs", "javascript", "js", "manager", "monitoring"],
  "pnpm": ["package", "manager"],
  "podman": ["container", "pods", "docker"],
  "poetry": ["package-manager", "python"],
  "polygon": ["ethereum", "erc20", "blockchain"],
  "portainer": ["docker", "kubernetes", "orchestrator"],
  "postcss": ["pre-processor", "css", "framework"],
  "postgresql": ["database"],
  "postman": ["tool", "testing"],
  "powershell": ["command-line", "shell", "terminal", "cli", "windows", "cmdlets"],
  "premierepro": ["editor", "video"],
  "primeng": ["angular", "ui", "component", "library", "framework"],
  "prisma": ["orm", "nodejs", "typescript"],
  "processing": ["java", "python", "android", "application", "ide", "framework"],
  "processwire": ["cms", "php", "framework"],
  "prolog": ["programming", "logic", "language", "open-source"],
  "prometheus": ["monitoring", "observability", "analysis"],
  "protractor": ["framework", "javascript"],
  "proxmox": ["container", "lxc", "virtual machine"],
  "pug": ["framework", "javascript", "nodejs"],
  "pulsar": ["open-source", "cross-platform", "editor"],
  "pulumi": ["infrastructure-as-code", "cloud"],
  "puppeteer": ["open-source", "devtools protocol", "testing", "extension"],
  "purescript": ["functional", "programming", "javascript"],
  "putty": ["ssh", "server"],
  "pycharm": ["jetbrains", "editor"],
  "pypi": ["python", "package", "programming"],
  "pyscript": ["browser", "python", "html", "framework"],
  "pytest": ["python", "framework", "testing"],
  "python": ["programming", "language"],
  "pytorch": ["programming", "framework", "machine-learning", "python"],
  "qodana": ["jetbrains", "code quality", "security"],
  "qt": ["framework"],
  "qtest": ["testing"],
  "quarkus": ["java", "framework"],
  "quasar": ["framework", "javascript"],
  "qwik": ["framework", "open-source"],
  "r": ["programming", "language"],
  "rabbitmq": ["message-broker", "open-source"],
  "racket": ["programming", "language"],
  "radstudio": ["editor", "IDE"],
  "rails": ["framework"],
  "railway": ["hosting", "platform", "deployment"],
  "rancher": ["kubernetes", "orchestrator"],
  "raspberrypi": ["arm", "computer"],
  "reach": ["web3", "blockchain", "development"],
  "react": ["framework"],
  "reactbootstrap": ["framework", "library", "frontend", "reactjs", "javascript"],
  "reactnative": ["framework"],
  "reactnavigation": ["routing", "navigation", "react native", "app", "open-source"],
  "reactrouter": ["framework", "react"],
  "readthedocs": ["documentation", "python", "open-source"],
  "realm": ["sql", "database", "cloud"],
  "rect": ["programming", "language"],
  "redhat": ["server", "linux"],
  "redis": ["server"],
  "redux": ["framework"],
  "reflex": ["framework", "python", "web"],
  "remix": ["framework", "fullstack", "web"],
  "renpy": ["programming", "game-engine", "engine", "python"],
  "replit": ["software"],
  "rexx": ["language"],
  "rider": ["jetbrains", "ide", "editor", "dotnet"],
  "rocksdb": ["database"],
  "rockylinux": ["os", "open-source", "linux"],
  "rollup": ["bundler", "build", "javascript"],
  "ros": ["robotics"],
  "rspec": ["ruby", "framework", "testing"],
  "rstudio": ["editor", "package", "statistics"],
  "ruby": ["programming", "language"],
  "rubymine": ["jetbrains", "editor"],
  "rust": ["programming", "language"],
  "rxjs": ["javascript", "library", "observability"],
  "safari": ["browser"],
  "salesforce": ["platform", "ecommerce"],
  "sanity": ["CMS"],
  "sass": ["pre-processor", "css"],
  "scala": ["programming", "language", "jvm"],
  "scalingo": ["cloud", "platform", "hosting"],
  "scikitlearn": ["machine-learning", "python", "tool", "library"],
  "sdl": ["library", "cross-platform", "multimedia", "game"],
  "selenium": ["webdrive", "automation"],
  "sema": ["software", "development", "company", "code-review", "open-source"],
  "sentry": ["monitoring", "analytics", "metrics"],
  "sequelize": ["database", "language"],
  "shopware": ["cloud", "platform"],
  "shotgrid": ["web-application", "autodesk", "project-management", "pipeline", "production-tool", "production-tracking"],
  "sketch": ["application"],
  "slack": ["chat"],
  "socketio": ["library", "networking", "websockets"],
  "solidity": ["programming", "language", "blockchain"],
  "solidjs": ["javascript", "framework", "frontend"],
  "sonarqube": ["tool", "security"],
  "sourceengine": ["game-engine", "valve", "javascript"],
  "sourcetree": ["version-control"],
  "spack": ["package-manager", "package", "manager", "python", "open-source"],
  "spicedb": ["database", "authorization", "access-control", "Zanzibar"],
  "splunk": ["platform", "data", "log", "monitoring"],
  "spring": ["framework"],
  "spss": ["package", "statistics"],
  "spyder": ["python", "ide", "editor", "data-science"],
  "sqlalchemy": ["python", "orm"],
  "sqldeveloper": ["tool", "database"],
  "sqlite": ["sql", "database", "db"],
  "ssh": ["security"],
  "stackblitz": ["IDE", "editor", "remote-development"],
  "stackoverflow": ["website", "development", "community"],
  "stata": ["analysis", "data", "data-science", "software", "statistics"],
  "stenciljs": ["framework", "ui"],
  "storybook": ["framework", "documentation", "ui"],
  "streamlit": ["python", "machine-learning", "data-science"],
  "styledcomponents": ["css", "javascript", "js", "library", "nodejs", "web"],
  "stylus": ["css", "pre-processor"],
  "subversion": ["svn", "version"],
  "sulu": ["cms", "platform"],
  "supabase": ["authentication", "cloud-computing-platform", "database", "storage"],
  "surrealdb": ["db", "database", "storage"],
  "svelte": ["javascript", "framework", "compiler"],
  "svgo": ["svg", "optimization", "tool", "javascript", "library", "node.js"],
  "swagger": ["development", "software", "tool"],
  "swift": ["language"],
  "swiper": ["library", "javascript", "open-source"],
  "symfony": ["framework", "php"],
  "tailwindcss": ["css", "framework"],
  "talos": ["container", "linux", "distribution"],
  "tauri": ["nodejs", "rust", "desktop", "framework", "programming"],
  "teleport": ["ssh", "security", "auth", "authentication", "infrastructure"],
  "tensorflow": ["library", "machine-learning", "deep-learning"],
  "terraform": ["deployment", "architecture", "automation"],
  "terramate": ["deployment", "devops", "automation"],
  "tex": ["typesetting-system", "markup", "tex"],
  "thealgorithms": ["organization", "algorithms"],
  "threedsmax": ["3d", "programming", "vfx", "graphic", "graphics", "game"],
  "threejs": ["javascript", "framework"],
  "thymeleaf": ["engine", "html", "java", "server"],
  "titaniumsdk": ["app", "mobile", "javascript", "cross-platform", "sdk"],
  "tmux": ["cli", "terminal", "multiplexer"],
  "tomcat": ["server"],
  "tortoisegit": ["git"],
  "towergit": ["git"],
  "traefikmesh": ["mesh", "kubernetes"],
  "traefikproxy": ["proxy", "router"],
  "travis": ["platform", "integration"],
  "trello": ["platform", "organize"],
  "trpc": ["typescript", "javascript", "typesafe", "api"],
  "turbo": ["spa", "js"],
  "twilio": ["api", "automation", "platform"],
  "twitter": ["auth"],
  "typescript": ["programming", "transpiler", "javascript", "language"],
  "typo3": ["cms", "php"],
  "ubuntu": ["os", "open-source", "linux"],
  "unifiedmodelinglanguage": ["modeling", "design", "language"],
  "unity": ["C#", "c-sharp", "csharp", "engine", "game-engine"],
  "unix": ["os"],
  "unrealengine": ["c++", "engine", "game-engine"],
  "uwsgi": ["hosting"],
  "v8": ["javascript-runtime", "framework", "javascript", "web", "cpp"],
  "vaadin": ["framework", "java", "web"],
  "vagrant": ["platform"],
  "vala": ["programming", "language"],
  "vault": ["tool", "security", "infrastructure"],
  "veevalidate": ["vuejs", "vuejs-library", "package"],
  "vercel": ["hosting", "platform", "deployment", "git"],
  "vertx": ["sdk", "java", "framework"],
  "vim": ["editor"],
  "visualbasic": ["programming", "language"],
  "visualstudio": ["editor"],
  "vite": ["web3", "blockchain", "DAG"],
  "vitejs": ["javascript", "build", "compiler", "esbuild"],
  "vitess": ["sharding", "database", "mysql"],
  "vitest": ["framework", "open-source", "testing", "vite"],
  "vscode": ["editor", "ide"],
  "vscodium": ["editor", "ide", "open-source"],
  "vsphere": ["hypervisor", "operating-system", "vmware"],
  "vuejs": ["framework"],
  "vuestorefront": ["framework"],
  "vuetify": ["css", "framework", "vuejs-library", "material-design"],
  "vulkan": ["api", "3d", "library", "graphics", "game"],
  "vyper": ["blockchain", "ethereum", "language", "programming", "python"],
  "waku": ["react", "javascript", "framework", "web"],
  "wasm": ["binary", "programming", "virtual machine", "web", "language"],
  "web3js": ["blockchain", "ecommerce"],
  "webflow": ["cms", "ecommerce"],
  "webgpu": ["graphics", "framework", "web"],
  "weblate": ["localization"],
  "webpack": ["package", "manager"],
  "webstorm": ["jetbrains", "editor"],
  "windows11": ["os"],
  "windows8": ["os"],
  "wolfram": ["data-science", "functional", "programming"],
  "woocommerce": ["ecommerce"],
  "wordpress": ["cms"],
  "xamarin": ["application", "programming", "editor", "ide", "ios", "mobile"],
  "xcode": ["application", "editor", "ide", "ios", "iphone", "mobile"],
  "xd": ["design", "editor", "ui"],
  "xml": ["markup", "language"],
  "yaml": ["data", "language"],
  "yarn": ["package", "manager", "javascript", "js"],
  "yii": ["php", "framework"],
  "yugabytedb": ["database", "relational", "sql", "scale", "open-source"],
  "yunohost": ["os"],
  "zend": ["php", "framework"],
  "zig": ["language"],
  "zsh": ["shell", "script", "scripting", "language", "command"],
  "zustand": ["framework"],
};
